apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-p9-governance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: sa-p9
  source:
    repoURL: https://github.com/AngelSGonza2107/GitOps-SA-B-202200263.git
    targetRevision: main
    path: environments/p9/governance
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=false, ServerSideApply=true]

