apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-p9-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: sa-p9
  source:
    repoURL: https://github.com/AngelSGonza2107/GitOps-SA-B-202200263.git
    targetRevision: main
    path: environments/p9/rendered
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
    retry:
      limit: 10
      backoff: { duration: 15s, factor: 2, maxDuration: 5m }

